kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: socialnetwork
  name: account-socialnetwork-manager-hjivr

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: socialnetwork
  name: role-socialnetwork-manager-hjivr
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-socialnetwork-manager-hjivr
  namespace: socialnetwork
subjects:
- kind: ServiceAccount
  name: account-socialnetwork-manager-hjivr
  namespace: socialnetwork
roleRef:
  kind: Role
  name: role-socialnetwork-manager-hjivr
  apiGroup: rbac.authorization.k8s.io
