apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: socialnetwork
  creationTimestamp: "2024-03-12T09:41:11Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.50.1
    helm.sh/chart: prometheus-25.17.0
  name: prometheus-server
  namespace: socialnetwork
  resourceVersion: "28574"
  uid: 8a636bf0-536c-4b72-b016-14d98a8c633d
spec:
  clusterIP: 10.98.167.169
  clusterIPs:
  - 10.98.167.169
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
